import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ThemeProvider } from "@/components/Providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { ReduxProvider } from "@/Redux/core/provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ActiveProjectProvider } from "@/components/Admin/AdminDashboard/Workspace/ActiveProjectContexts/ActiveProjectContext";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ReduxProvider>
                        <TooltipProvider>
                            <ActiveProjectProvider
                                autoExpireHours={24}
                                enablePersistence={true}
                                enableNotifications={true}
                            >
                                {children}
                            </ActiveProjectProvider>
                        </TooltipProvider>
                        <Toaster />

                    </ReduxProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
